{{- $global := . }}
{{- range $component, $cfg := (fromYaml (include "fire.components" .)) }}
{{- with $global }}
{{-  $values := mustMergeOverwrite (deepCopy .Values.fire ) ($cfg | default dict)}}
---
apiVersion: apps/v1
kind: {{ $cfg.kind }}
metadata:
  name: {{ $cfg.name }}
  labels:
    {{- include "fire.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $component | quote }}
spec:
{{- if eq $values.kind "StatefulSet" }}
  serviceName: {{ $values.name }}-headless
  podManagementPolicy: Parallel
{{- end }}
{{- if hasKey $values "replicaCount" }}
  replicas: {{ $values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "fire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $component | quote }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with $values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "fire.templateLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ $component | quote }}
        name: {{ if eq $component "all" }}"fire"{{ else }}"{{ $component }}"{{ end }}
    spec:
      {{- with $values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fire.serviceAccountName" . }}
      securityContext:
        {{- toYaml $values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ if eq $component "all" }}"fire"{{ else }}"{{ $component }}"{{ end }}
          securityContext:
            {{- toYaml $values.securityContext | nindent 12 }}
          image: "{{ $values.image.repository }}:{{ $values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          args:
            - "-target={{ $component }}"
            - "-memberlist.cluster-label={{ .Release.Namespace }}-{{ include "fire.fullname" .}}"
            - "-memberlist.join={{ include "fire.fullname" .}}-memberlist.{{ .Release.Namespace }}.svc.cluster.local."
          {{- if eq $component "agent" }}
            - "-client.url=http://{{ include "fire.fullname" . }}-distributor.{{ .Release.Namespace }}.svc.cluster.local.:{{ $values.service.port }}"
          {{- end }}
            - "-config.file=/etc/fire/config.yaml"
          {{- range $key, $value := $values.extraArgs }}
            - "-{{ $key }}={{ $value }}"
          {{- end }}
          {{- with $values.extraEnvVars }}
          env:
           {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
           {{- end }}
          {{- end }}
          ports:
            - name: {{ $values.service.port_name }}
              containerPort: {{ $values.service.port }}
              protocol: TCP
            - name: {{ $values.memberlist.port_name }}
              containerPort: {{ $values.memberlist.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ $values.service.port_name }}
          volumeMounts:
            - name: config
              mountPath: /etc/fire/config.yaml
              subPath: config.yaml
            - name: data
              mountPath: /data
            {{- with $values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml $values.resources | nindent 12 }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- with $values.extraVolumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: config
          configMap:
            name: {{ include "fire.fullname" . }}-config
  {{- $persistence := $values.persistence }}
  {{- if not $persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if $persistence.existingClaim}}
        - name: data
          persistentVolumeClaim:
            claimName: {{ $persistence.existingClaim }}
  {{- else if ne $cfg.kind "StatefulSet"}}
        - name: data
          persistentVolumeClaim:
            claimName: {{ $cfg.name }}-data
  {{- else }}
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        {{- toYaml $persistence.annotations | nindent 8 }}
    spec:
      accessModes:
        {{- toYaml $persistence.accessModes | nindent 8 }}
      resources:
        requests:
          storage: {{ $persistence.size | quote }}
      storageClassName: {{ $persistence.storageClassName }}
      {{- if $persistence.selector }}
      selector:
        {{- toYaml $persistence.selector | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
