name: e2e
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Cancel any running workflow for the same branch when new commits are pushed.
  # We group both by ref_name (available when CI is triggered by a push to a branch/tag)
  # and head_ref (available when CI is triggered by a PR).
  group: "e2e-${{ github.ref_name }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  regular-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: yarn
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.8
      - run: yarn --frozen-lockfile
      - run: make build
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          wait-on: http://localhost:4100
          start: ./phlare
          config-file: cypress/ci.ts
  base-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: yarn
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.8
      - run: yarn --frozen-lockfile
      - run: make build
      - name: run nginx with /pyroscope
        run: docker-compose -f scripts/base-url/docker-compose.yaml up -d
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          wait-on: http://localhost:8080/foobar/
          start: ./phlare -base-url=/foobar/
          config-file: cypress/ci-base-path.ts

