name: ci
on:
  push:
    branches:
      - main
      - r[0-9]+ # Trigger builds after a push to weekly branches
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.7, 1.19.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      # Get values for cache paths to be used in later steps
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GO_MOD_SSH_PRIVATE_KEY }}
      - name: Enfore SSH for github.com
        run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      - name: Go Mod
        run: make check/go/mod
        if: matrix.os == 'ubuntu-latest'
      - name: Format
        run: make fmt check/unstaged-changes
        if: matrix.os == 'ubuntu-latest'
      - name: Test
        run: make go/test

  lint:
    strategy:
      matrix:
        go-version: [1.18.7, 1.19.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      # Get values for cache paths to be used in later steps
      - id: go-cache-paths
        run: |
          echo "::set-output name=go-build::$(go env GOCACHE)"
          echo "::set-output name=go-mod::$(go env GOMODCACHE)"

      # Cache go build cache, used to speedup go test
      - name: Go Build Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-build }}
          key: ${{ runner.os }}-go-build-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}

      # Cache go mod cache, used to speedup builds
      - name: Go Mod Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.go-cache-paths.outputs.go-mod }}
          key: ${{ runner.os }}-go-mod-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GO_MOD_SSH_PRIVATE_KEY }}
      - name: Enfore SSH for github.com
        run: git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      - name: Run linter
        run: make lint
      - name: Check helm manifests
        run: make helm/check

  test-docs:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: "actions/checkout@v3"
      - name: "Test docs"
        run: make docs/test
      - name: "Validate docs"
        run: make docs/validate

  build-image:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GO_MOD_SSH_PRIVATE_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.7
      - name: build binaries
        run: make go/mod go/bin
      - name: Build image Phlare
        run: make docker-image/phlare/build "BUILDX_ARGS=--cache-from=type=gha --cache-to=type=gha"

  build-image-grafana:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GO_MOD_SSH_PRIVATE_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        run: make docker-image/grafana/build "BUILDX_ARGS=--cache-from=type=gha --cache-to=type=gha"

  build-push:
    if: github.event_name == 'push' && github.repository == 'grafana/phlare'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GO_MOD_SSH_PRIVATE_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.7
      - name: build binaries
        run: make go/mod go/bin
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Phlare Build & push multi-arch image
        id: build-push
        run: |
          make docker-image/phlare/push "BUILDX_ARGS=--cache-from=type=gha --cache-to=type=gha"

  build-push-grafana:
    if: github.event_name == 'push' && github.repository == 'grafana/phlare'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.GO_MOD_SSH_PRIVATE_KEY }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}
      - name: Build & push multi-arch image
        id: build-push-grafana
        run: |
          make docker-image/grafana/push "BUILDX_ARGS=--cache-from=type=gha --cache-to=type=gha"

  deploy-phlare-dev-001:
    if: github.event_name == 'push' && github.repository == 'grafana/phlare'
    runs-on: ubuntu-latest
    needs: [build-push, build-push-grafana]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Deploy to phlare-dev-001
        run: |
          git config --global url."https://grafanabot:${{ secrets.GRAFANABOT_PAT }}@github.com/grafana/deployment_tools".insteadOf "https://github.com/grafana/deployment_tools"
          make docker-image/phlare/deploy-dev-001
        env:
          GITHUB_TOKEN: ${{ secrets.GRAFANABOT_PAT }}
